version: "3.9"

networks:
  front:
  back:

services:
  app:
    build: # frontend
      context: ./app
      dockerfile: Dockerfile
    environment:
      TZ: Asia/Tokyo
    ports:
      - "3007:3007"
    command: sh -c 'yarn && yarn dev'
    volumes:
      - ./app:/usr/src/app
    networks:
      - front
      - back
